/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vite-plugin-vue-middleware. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

export {}

declare module 'vue-router' {
  interface RouteMeta {
    middleware?:
      | 'abort-navigation'
      | 'named-one'
      | 'named-two'
      | 'redirect-to-about'
      | ('abort-navigation' | 'named-one' | 'named-two' | 'redirect-to-about')[];
  }
}
