import fs from 'node:fs/promises';

import path from 'pathe';

import type { MiddlewareFile } from './parse';

/**
 * Render the contents of the generated `.d.ts` file.
 *
 * Pure function — no filesystem side effects.
 */
function buildDtsContent(middlewareFiles: MiddlewareFile[]): string {
  const namedKeys = middlewareFiles.filter((m) => !m.isGlobal).map((m) => `"${m.name}"`);

  const typeUnion = namedKeys.length > 0 ? namedKeys.join(' | ') : 'string';

  return `/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vite-plugin-vue-middleware. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

export {}

declare module 'vue-router' {
  interface RouteMeta {
    middleware?: ${typeUnion} | (${typeUnion})[]
  }
}
`;
}

/**
 * Write the generated `.d.ts` file to disk.
 *
 * Skips the write entirely when the on-disk content is byte-identical, avoiding spurious
 * TypeScript-server reloads in editors during HMR.
 *
 * Extends RouteMeta of vue-router based on current middleware files.
 *
 * @param middlewareFiles Discovered middleware metadata
 * @param dtsPath Absolute output path
 */
export async function generateDts(
  middlewareFiles: MiddlewareFile[],
  dtsPath: string,
): Promise<void> {
  const dtsContent = buildDtsContent(middlewareFiles);

  let existing: string | undefined;
  try {
    existing = await fs.readFile(dtsPath, 'utf-8');
  } catch {
    // File does not exist yet — fall through to write
  }

  if (existing === dtsContent) return;

  await fs.mkdir(path.dirname(dtsPath), { recursive: true });
  await fs.writeFile(dtsPath, dtsContent, 'utf-8');
}
