import fs from 'node:fs';
import path from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';

export interface Options {
  /**
   * 包含 middleware 的目錄路徑，相對於專案根目錄
   * @default 'src/middleware'
   */
  middlewareDir?: string;
  /**
   * 是否自動生成 TypeScript 宣告檔，可傳入路徑字串
   * @default true
   */
  dts?: boolean | string;
}

const VIRTUAL_MODULE_ID = 'virtual:vue-middleware';
const RESOLVED_VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID;

interface MiddlewareFile {
  name: string;
  path: string;
  isGlobal: boolean;
  order: number;
}

// 遞迴讀取目錄下的所有檔案
function walk(dir: string, fileList: string[] = []): string[] {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walk(fullPath, fileList);
    } else {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

// 將 Windows 路徑轉為 posix
function normalizePath(p: string): string {
  return p.split(path.sep).join('/');
}

// 解析 middleware 目錄並產生清單
function parseMiddlewareFiles(dir: string): MiddlewareFile[] {
  const allFiles = walk(dir);
  const middlewareFiles: MiddlewareFile[] = [];

  for (const fullPath of allFiles) {
    if (!fullPath.endsWith('.ts') && !fullPath.endsWith('.js')) continue;

    const relPath = normalizePath(path.relative(dir, fullPath));
    const nameWithoutExt = relPath.replace(/\.[^.]+$/, '');

    let isGlobal = false;
    let name = nameWithoutExt;
    let order = 0;

    if (name.endsWith('.global')) {
      isGlobal = true;
      name = name.slice(0, -7);
    }

    const parts = name.split('/');
    const lastPart = parts[parts.length - 1];
    const match = lastPart.match(/^(\d+)\.(.+)$/);

    if (match) {
      order = parseInt(match[1], 10);
      parts[parts.length - 1] = match[2];
      name = parts.join('-');
    } else {
      name = parts.join('-');
    }

    middlewareFiles.push({
      name,
      path: normalizePath(fullPath),
      isGlobal,
      order,
    });
  }

  return middlewareFiles.sort((a, b) => a.order - b.order);
}

// 產生 d.ts
function generateDts(middlewareFiles: MiddlewareFile[], dtsPath: string) {
  const namedMiddlewares = middlewareFiles.filter((m) => !m.isGlobal).map((m) => `"${m.name}"`);

  const typeUnion = namedMiddlewares.length > 0 ? namedMiddlewares.join(' | ') : 'string';

  const dtsContent = `/* eslint-disable */
/* prettier-ignore */
// Generated by vite-plugin-vue-middleware

export {}

declare module 'vue-router' {
  interface RouteMeta {
    middleware?: ${typeUnion} | (${typeUnion})[]
  }
}
`;
  fs.writeFileSync(dtsPath, dtsContent, 'utf-8');
}

export default function vitePluginVueMiddleware(options: Partial<Options> = {}): Plugin {
  const { middlewareDir = 'src/middleware', dts = true } = options;

  let resolvedDir: string;
  let resolvedDtsPath: string | undefined;

  return {
    name: 'vite-plugin-vue-middleware',
    configResolved(config: ResolvedConfig) {
      resolvedDir = path.resolve(config.root, middlewareDir);

      if (dts) {
        if (typeof dts === 'string') {
          resolvedDtsPath = path.resolve(config.root, dts);
        } else {
          // 優先產放在 src 目錄下，以確保大多數 Vue 專案的 tsconfig 能自動 include
          const srcPath = path.resolve(config.root, 'src');
          const targetDir = fs.existsSync(srcPath) ? srcPath : config.root;
          resolvedDtsPath = path.resolve(targetDir, 'middleware.d.ts');
        }
      }
    },
    buildStart() {
      // 確保在編譯開始時產生（或更新）型別檔
      if (dts && resolvedDir) {
        const files = parseMiddlewareFiles(resolvedDir);
        if (resolvedDtsPath) {
          generateDts(files, resolvedDtsPath);
        }
      }
    },
    resolveId(id: string) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
    },
    load(id: string) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        const files = parseMiddlewareFiles(resolvedDir);

        let code = `import { setupMiddleware as _setup } from "vite-plugin-vue-middleware/runtime";\n`;
        code += `export { defineMiddleware } from "vite-plugin-vue-middleware/runtime";\n\n`;

        const globalImports: string[] = [];
        const namedImports: string[] = [];

        files.forEach((file, index) => {
          const importName = `__middleware_${index}`;
          code += `import ${importName} from "${file.path}";\n`;
          if (file.isGlobal) {
            globalImports.push(importName);
          } else {
            namedImports.push(`"${file.name}": ${importName}`);
          }
        });

        code += `\nexport const globalMiddleware = [${globalImports.join(', ')}];\n`;
        code += `export const namedMiddleware = { ${namedImports.join(', ')} };\n`;
        code += `export const setupMiddleware = (router) => _setup(router, globalMiddleware, namedMiddleware);\n`;

        return code;
      }
    },
    configureServer(server) {
      const _handleFileChange = (file: string) => {
        const normalizedFile = normalizePath(file);
        const normalizedDir = normalizePath(resolvedDir);

        if (normalizedFile.startsWith(normalizedDir)) {
          // 重新產生型別定義檔
          if (dts && resolvedDtsPath) {
            const files = parseMiddlewareFiles(resolvedDir);
            generateDts(files, resolvedDtsPath);
          }

          // 使虛擬模組失效
          const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
          if (mod) {
            server.moduleGraph.invalidateModule(mod);
          }

          // 觸發全頁重新整理，確保 runtime 狀態同步
          server.ws.send({ type: 'full-reload' });
        }
      };

      server.watcher.on('add', _handleFileChange);
      server.watcher.on('unlink', _handleFileChange);
    },
  };
}
