import fs from 'node:fs/promises';

import path from 'pathe';
import { glob } from 'tinyglobby';

/** Middleware file information */
export type MiddlewareFile = {
  name: string;
  path: string;
  isGlobal: boolean;
  order: number;
};

/**
 * Parse middleware directory and generate a file list
 *
 * Reads JS/TS files in the specified directory and parses naming rules (EAFP)
 *
 * @param {string} dir - Directory path
 * @param {string[]} exclude - List of glob patterns to exclude
 * @returns {Promise<MiddlewareFile[]>} Parsed middleware file list
 */
export async function parseMiddlewareFiles(
  dir: string,
  exclude: string[] = [],
): Promise<MiddlewareFile[]> {
  try {
    await fs.access(dir);
  } catch {
    return [];
  }

  const allFiles = await glob(['**/*.{ts,js}'], {
    cwd: dir,
    absolute: true,
    ignore: exclude,
  });

  const middlewareFiles: MiddlewareFile[] = [];

  for (const fullPath of allFiles) {
    const relPath = path.relative(dir, fullPath);
    const nameWithoutExt = relPath.replace(/\.[^.]+$/, '');

    let isGlobal = false;
    let name = nameWithoutExt;
    let order = 0;

    if (name.endsWith('.global')) {
      isGlobal = true;
      name = name.slice(0, -7);
    }

    const parts = name.split('/');
    const lastPart = parts[parts.length - 1];
    const match = lastPart.match(/^(\d+)\.(.+)$/);

    if (match) {
      order = parseInt(match[1], 10);
      parts[parts.length - 1] = match[2];
      name = parts.join('-');
    } else {
      name = parts.join('-');
    }

    middlewareFiles.push({
      name,
      path: fullPath,
      isGlobal,
      order,
    });
  }

  return middlewareFiles.sort((a, b) => a.order - b.order);
}

/**
 * Generate TypeScript declaration file (d.ts)
 *
 * Extends RouteMeta of vue-router based on current middleware files
 *
 * @param {MiddlewareFile[]} middlewareFiles - List of middleware files
 * @param {string} dtsPath - Output file path
 * @returns {Promise<void>}
 */
export async function generateDts(
  middlewareFiles: MiddlewareFile[],
  dtsPath: string,
): Promise<void> {
  const namedMiddlewares = middlewareFiles.filter((m) => !m.isGlobal).map((m) => `"${m.name}"`);

  const typeUnion = namedMiddlewares.length > 0 ? namedMiddlewares.join(' | ') : 'string';

  const dtsContent = `/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vite-plugin-vue-middleware. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

export {}

declare module 'vue-router' {
  interface RouteMeta {
    middleware?: ${typeUnion} | (${typeUnion})[]
  }
}
`;
  const dtsDir = path.dirname(dtsPath);
  await fs.mkdir(dtsDir, { recursive: true });
  await fs.writeFile(dtsPath, dtsContent, 'utf-8');
}
